"""empty message

Revision ID: 29a1c059850b
Revises: None
Create Date: 2014-09-21 12:54:25.205134

"""

# revision identifiers, used by Alembic.
revision = '29a1c059850b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=25), nullable=True))
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
